[package]
name = "handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
secp256k1 = { version = "0.29.0" }
ecies = { version = "0.2.7", features = ["std"] }
rlp = { version = "0.5.2", features = ["derive"] }
keccak-hash = "0.10.0"
regex = "1.10.5"
hex = "0.4.3"
rand = "0.8.5"